added resource groups ids output
Azure/terraform-azurerm-lz-vending pull request #185
Opened 2023-04-19 08:43 UTC by ppodevlab

# Overview/summary
Module now returns a list of resource groups created by the virtualnetwork submodule.

## This PR fixes/adds/changes/removes
Fixes #184 

## As part of this pull request I have

- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-lz-vending/pulls)
- [X] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-lz-vending/issues), for tracking and closure.
- [X] Run and `make fmt` & `make docs` to format your code and update documentation.
- [ ] Created unit and deployment tests and provided evidence.
- [X] Updated relevant and associated documentation.

2023-04-19 08:47 UTC, ppodevlab commented
> @microsoft-github-policy-service agree company="Microsoft"

@microsoft-github-policy-service agree company="Enreach"

2023-04-19 15:25 UTC, matt-FFFFFF commented
Hey @ppodevlab 

Thanks for your PR. I'll review it shortly.

2023-04-20 16:14 UTC, matt-FFFFFF requested changes
Hi, looks great just some minor changes please

2023-04-20 16:14 UTC, matt-FFFFFF commented on outputs.tf
> +output "resource_group_ids" {
please can you rename this to:

```suggestion
output "virtual_network_resource_group_ids" {
```

This means we can add other outputs for future submodules that may create RGs

2023-04-20 16:14 UTC, matt-FFFFFF commented on locals.tf
> +  resource_group_ids = try(module.virtualnetwork[0].resource_group_ids, {})
Please can we rename this as per other comments

```suggestion
  virtual_network_resource_group_ids = try(module.virtualnetwork[0].resource_group_ids, {})
```

2023-04-20 16:14 UTC, matt-FFFFFF commented on outputs.tf
> +  value       = local.resource_group_ids
```suggestion
  value       = local.virtual_network_resource_group_ids
```

2023-04-21 06:40 UTC, ppodevlab commented
> Hi, looks great just some minor changes please

done

2023-04-24 12:16 UTC, merged

2023-04-30 07:33 UTC, matt-FFFFFF commented
Will be in next minor with #187