Feat/umi
Azure/terraform-azurerm-lz-vending pull request #219
Opened 2023-06-24 12:13 UTC by matt-FFFFFF

# Overview/summary

Adds support for creating a user assigned managed ideneity in the supplied subscription.

This is useful in two scenarios:

- granting access from your devops cicd pipeline runner virtual machine
- using with cloud based cicd runners and OpenID Connect, e.g. GH actions or Terraform cloud

## This PR fixes/adds/changes/removes

1. *Replace me*

### Breaking changes

1. *Replace me*

## Testing evidence

Please provide testing evidence to show that your Pull Request works/fixes as described and documented above.

## As part of this pull request I have

- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-lz-vending/pulls)
- [ ] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-lz-vending/issues), for tracking and closure.
- [ ] Run and `make fmt` & `make docs` to format your code and update documentation.
- [ ] Created unit and deployment tests and provided evidence.
- [ ] Updated relevant and associated documentation.

2023-06-29 09:00 UTC, jtracey93 submitted a review, later dismissed

2023-06-30 14:54 UTC, jtracey93 requested changes

2023-06-30 14:54 UTC, jtracey93 commented on modules/resourceprovider/header.md
> +# ALZ landing zone resource provider submodule
ALZ?

2023-06-30 14:54 UTC, jtracey93 commented on modules/resourceprovider/README.md
> +# ALZ landing zone resource provider submodule
ALZ?

2023-06-30 14:56 UTC, matt-FFFFFF commented on modules/resourceprovider/header.md
> +# ALZ landing zone resource provider submodule
fair!

2023-06-30 14:59 UTC, jtracey93 approved these changes
LGTM

2023-06-30 15:07 UTC, merged