feat(subscription): optional use of AzAPI for Subscription creation
Azure/terraform-azurerm-lz-vending pull request #234
Opened 2023-08-02 10:31 UTC by danwatco

# Overview/summary

This PR adds functionality to create a subscription using the `azapi_resource` resource type rather than using `azurerm_subscription`. This is useful in situations where the principal running Terraform doesn't have access to the default management group where subscriptions are created. By using the API, we can provide the `managementGroupId` parameter and the subscription is then created in the provided management group, avoiding the need to have creation permissions underneath the default management group.

Written unit and deployment tests (feedback welcome, my first time writing Go tests). Unable to run deployment tests so needs some testing there. 

## Testing evidence
<img width="947" alt="image" src="https://github.com/Azure/terraform-azurerm-lz-vending/assets/6568235/e49a9e3e-d962-47c5-8434-5030948721e8">

<img width="1110" alt="image" src="https://github.com/Azure/terraform-azurerm-lz-vending/assets/6568235/def85735-0501-498f-a315-e73422984e7e">

There is some concerns that the management group association may cause an import error but yet to be tested.

## As part of this pull request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-lz-vending/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-lz-vending/issues), for tracking and closure.
- [x] Run and `make fmt` & `make docs` to format your code and update documentation.
- [x] Created unit and deployment tests and provided evidence.
- [x] Updated relevant and associated documentation.

2023-08-02 18:39 UTC, matt-FFFFFF commented
Thanks @danwatco this looks great. Appreciate you taking the time to create some tests too.

I think one scenario that needs to be tested with deployment tests is one of using AzAPI to create the subscription alias and then AzureRM to manage the management group association.

If you are happy to copy one of the other deployment tests in the subscription submodule then feel free to modify that, if not I can do it.

2023-08-03 08:07 UTC, danwatco commented
> Thanks @danwatco this looks great. Appreciate you taking the time to create some tests too.
> 
> I think one scenario that needs to be tested with deployment tests is one of using AzAPI to create the subscription alias and then AzureRM to manage the management group association.
> 
> If you are happy to copy one of the other deployment tests in the subscription submodule then feel free to modify that, if not I can do it.

Have had a shot here - feel free to change/update

2023-09-25 13:04 UTC, jaredfholgate requested changes

2023-09-25 13:04 UTC, jaredfholgate commented on modules/subscription/main.tf
>    count               = var.subscription_management_group_association_enabled ? 1 : 0
@luke-taylor You don't need this block if using AzAPI, so you can count = 0 it.

2023-09-28 12:32 UTC, matt-FFFFFF commented
Thanks for this @danwatco - @luke-taylor has implemented this in #253

2023-09-28 12:32 UTC, closed without merging