feat: enable unidirectional vnet peering
Azure/terraform-azurerm-lz-vending pull request #246
Opened 2023-08-31 08:17 UTC by jaredfholgate

# Overview/summary

This change adds a new attribute to the vnet variable to support unidirectional peering.

## This PR fixes/adds/changes/removes

N/A

### Breaking changes

None, defaults to `both` which was the previous behaviour.

## Testing evidence

Unit tests have been added to cover both cases.

## As part of this pull request I have

- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-lz-vending/pulls)
- [x] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-lz-vending/issues), for tracking and closure.
- [x] Run and `make fmt` & `make docs` to format your code and update documentation.
- [x] Created unit and deployment tests and provided evidence.
- [x] Updated relevant and associated documentation.

2023-09-06 10:08 UTC, matt-FFFFFF requested changes

2023-09-06 10:08 UTC, matt-FFFFFF commented on modules/virtualnetwork/locals.tf
> +      peering_direction   = contains(local.valid_peering_directions, coalesce(lower(v.hub_peering_direction), local.peering_direction_both)) ? coalesce(lower(v.hub_peering_direction), local.peering_d
What are your thoughts on using a variable validation rule here, with for loop and alltrue() Could we simplify this?

2023-09-06 10:08 UTC, matt-FFFFFF commented on tests/virtualnetwork/virtualnetwork_test.go
> +	// The additional two are the inbound & outbound peering
```suggestion
	// We want 9 resources here, 1 more than the TestVirtualNetworkCreateValid test
	// The additional one is the outbound peering
```

2023-09-06 11:56 UTC, matt-FFFFFF commented on modules/virtualnetwork/locals.tf
> +      peering_direction   = contains(local.valid_peering_directions, coalesce(lower(v.hub_peering_direction), local.peering_direction_both)) ? coalesce(lower(v.hub_peering_direction), local.peering_d
Ok fair, happy with this

2023-09-06 12:02 UTC, matt-FFFFFF commented
Doing specific deployment test for VirtualNetwork https://github.com/Azure/terraform-azurerm-lz-vending/actions/runs/6096771492

2023-09-06 12:42 UTC, matt-FFFFFF requested changes

2023-09-15 10:51 UTC, matt-FFFFFF requested changes

2023-09-15 10:51 UTC, matt-FFFFFF commented on tests/virtualnetwork/virtualnetworkDeploy_test.go
> +	testDir := "testdata/" + t.Name()
```suggestion
	testDir := ""
```

2023-09-15 10:51 UTC, matt-FFFFFF commented on tests/virtualnetwork/virtualnetworkDeploy_test.go
> +	testDir := "testdata/" + t.Name()
@jaredfholgate please can you fix this to enable the deployment tests to run?

The test dir is inly required when calling the module from another root module.

2023-09-21 11:25 UTC, jaredfholgate commented
@matt-FFFFFF Apologies for the delay. I have made the fix to the test and taken latest from main.

2023-09-21 15:25 UTC, merged