feat(roleassignment): add `condition` and `condition_version` to role assignment.
Azure/terraform-azurerm-lz-vending pull request #285
Opened 2023-11-23 13:00 UTC by tcharewicz

# Overview/summary

I would like to create Role Assignment with Condition, currently terraform resource allow for this operation

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment

## This PR fixes/adds/changes/removes

1. Adds condition and condition_version on resource azurerm_role_assignment

### Breaking changes

No Breaking changes. Only recreation of role assignment need to be done in a case of addition this two variable. 

[condition](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment#condition) - (Optional) The condition that limits the resources that the role can be assigned to. **Changing this forces a new resource to be created.**

[condition_version](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment#condition_version) - (Optional) The version of the condition. Possible values are 1.0 or 2.0. **Changing this forces a new resource to be created.**

## Testing evidence

Please provide testing evidence to show that your Pull Request works/fixes as described and documented above.

## As part of this pull request I have

- [OK] Checked for duplicate [Pull Requests](https://github.com/Azure/terraform-azurerm-lz-vending/pulls)
- [OK] Associated it with relevant [issues](https://github.com/Azure/terraform-azurerm-lz-vending/issues), for tracking and closure.
- [OK] Run and `make fmt` & `make docs` to format your code and update documentation.
- [OK] Created unit and deployment tests and provided evidence.
- [??] Updated relevant and associated documentation.

2023-11-27 13:37 UTC, matt-FFFFFF requested changes

2023-11-27 13:37 UTC, matt-FFFFFF commented on variables.roleassignment.tf
> +- `condition`: (optional) A condition to apply to the role assignment. See https://learn.microsoft.com/en-us/azure/role-based-access-control/conditions-custom-security-attributes for more details.
Please can you wrap these URLs as Markdown links, e.g. [link](http://foo)

2023-11-28 11:27 UTC, tcharewicz commented
@microsoft-github-policy-service agree [company="Ringier Axel Springer Polska"]

2023-11-28 11:28 UTC, tcharewicz commented
@microsoft-github-policy-service agree
@microsoft-github-policy-service agree company="Ringier Axel Spirnger Polska"

2023-11-30 21:06 UTC, matt-FFFFFF approved these changes

2023-12-01 09:01 UTC, merged